site_name: Ninefold
site_url: http://help.ninefold.com
site_description: Ninefold - Ruby on Rails hosting and app deployment
dev_addr: '0.0.0.0:8000'
repo_url: https://github.com/ninefold/docs/

# use_directory_urls: true
# include_search: true

theme_dir: ./theme/mkdocs/
# theme_center_lead: false
site_favicon: favicon.ico
google_analytics: ['UA-20888012-1', 'ninefold.com']

pages:

# About
- ['index.md', 'Home']

# Getting Started
- ['getstarted/how_to_deploy_an_app.md', 'Getting Started', 'How to deploy an app']
- ['getstarted/how_to_install_and_utilize_the_cli.md', 'Getting Started', 'How to install and utilize the CLI']
- ['getstarted/how_to_migrate_from_heroku.md', 'Getting Started', 'How to migrate from Heroku']
- ['getstarted/how_ninefold_works_with_github_bitbucket_and_git_url.md', 'Getting Started', 'How Ninefold works with Github, Bitbucket and Git URL']
- ['getstarted/exporting_and_importing_postgresql_data.md', 'Getting Started', 'Exporting and importing PostgreSQL data']
- ['getstarted/how_to_deploy_diaspora.md', 'Getting Started', 'How to deploy Diaspora on Ninefold']

# App Deployment
# - ['index.md', 'About', 'Ninefold']
- ['apps/deployment_with_continuous_integration_ci.md', 'App Deployment', 'Deployment with continuous integration (CI)']
- ['apps/deploying_a_rails_app_with_your_own_database.md', 'App Deployment', 'Deploying a Rails app with your own database']
- ['apps/asset_precompile_on_ninefold.md', 'App Deployment', 'Asset precompilation on Ninefold']
- ['apps/setting_up_deployment_notifications.md', 'App Deployment', 'Setting up deployment notifications']
- ['apps/zero_downtime_deployment_for_your_ninefold_rails_app.md', 'App Deployment', 'Zero downtime deployment for your Rails app']
- ['apps/Setting_and_changing_your_apps_configuration_and_infrastructure.md', 'App Deployment', 'Setting and Changing Your App Configuration and Infrastructure']
- ['apps/private_gem_repos_on_github_&_bitbucket.md', 'App Deployment', 'Private gem repos on GitHub and Bitbucket']
- ['apps/what_happens_and_what_gets_built_on_a_rails_app_deployment.md', 'App Deployment', 'What happens and what gets built when you deploy your app']
- ['apps/ssl_management_for_rails_apps.md', 'App Deployment', 'SSL for Rails Apps']
- ['apps/dns_management_for_rails_apps.md', 'App Deployment', 'DNS Management for Rails Apps']
- ['apps/adding_sendgrid_to_your_rails_app.md', 'App Deployment', 'Adding Sendgrid to Your Rails App']
- ['apps/creating_scheduled_tasks_in_rails.md', 'App Deployment', 'Creating scheduled tasks in Rails']
- ['apps/backing_up_and_restoring_your_rails_db.md', 'App Deployment', 'Backing up and Restoring Your Database']
- ['apps/redeploying_an_app.md', 'App Deployment', 'Redeploying an app']
- ['apps/postgres_and_postgis_and_modules.md', 'App Deployment', 'Postgres, PostGIS, and Postgres Modules']
- ['apps/how_to_utilize_a_cdn_with_ninefold.md', 'App Deployment', 'How to Utilize a CDN with Ninefold (S3 and CloudFront)']
- ['apps/upgrading_from_rails_40_to_41.md', 'App Deployment', 'Upgrading from Rails 4.0 to 4.1']

# Servers
- ['servers/docker.md', 'Servers', 'Docker containers']
- ['servers/create.md', 'Servers', 'How to create a server']
- ['servers/resize.md', 'Servers', 'How to resize your server']
- ['servers/liveview.md', 'Servers', 'How to access your server with live view']
- ['servers/clone.md', 'Servers', 'How to clone a server']
- ['servers/how_to_attach_and_upload_an_iso.md', 'Servers', 'How to upload and attach an ISO']
- ['servers/index.md', 'Servers', 'How to create a template from your server']
- ['servers/index.md', 'Servers', 'How to add storage volumes']
- ['servers/how_to_view_attached_and_detached_storage_volumes.md', 'Servers', 'How to view attached and detached storage volumes']
- ['servers/index.md', 'Servers', 'How to detach then reattach a storage volume']
- ['servers/index.md', 'Servers', 'Using backups to protect your data']
- ['servers/index.md', 'Servers', 'New server username and password']
- ['servers/index.md', 'Servers', 'Reset your server password']
- ['servers/index.md', 'Servers', 'How to connect to your server using SSH / RDP']
- ['servers/index.md', 'Servers', 'How to activate Windows Server']
- ['servers/microsoft.md', 'Servers', 'Microsoft licensing - Can I use my existing software and licenses?']

# Networking
- ['networking/index.md', 'Networking', 'How to enable "Ninefold Net" inter-zone networking']
- ['networking/index.md', 'Networking', 'Using multiple regions - an overview']
- ['networking/index.md', 'Networking', 'Copying or moving servers between regions']
- ['networking/index.md', 'Networking', 'DNS management for servers']
- ['networking/index.md', 'Networking', 'Setup load balancing (single zone)']
- ['networking/index.md', 'Networking', 'Setting up static NAT & port forward for IP addresses']
- ['networking/index.md', 'Networking', 'How to open firewall ports']
- ['networking/index.md', 'Networking', 'How to setup global load balancing for servers']
- ['networking/index.md', 'Networking', 'How to delegate your domain to Ninefold']
- ['networking/index.md', 'Networking', 'How to release or unassign your IP addresses']
- ['networking/index.md', 'Networking', 'How to use multiple IP addresses on a server']

# Accounts and Billing
- ['billing/freetrial.md', 'Accounts & Billing', 'Free trial']
- ['billing/createuser.md', 'Accounts & Billing', 'Creating additional users']
- ['billing/closeaccount.md', 'Accounts & Billing', 'How to close your account']
- ['billing/faq.md', 'Accounts & Billing', 'Billing FAQ']

# Reference
- ['reference/faq.md', 'Reference', 'FAQ']
- ['reference/apdex.md', 'Reference', 'Apdex to measure user satisfaction']
- ['reference/API.md', 'Reference', 'Using the API (v2)']
- ['reference/contributing.md', 'Reference', 'Contribute to our docs']
